services:
  nntp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nntp_web_client
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./dist:/app/dist
      - ./server.js:/app/server.js
      - ./backend:/app/backend
      - ./frontend/src/data:/app/frontend/src/data
      - ./downloads:/app/downloads
      - ./temp:/app/temp
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - default
      - shared-network

networks:
  shared-network:
    external: true
