services:
  nntp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nntp_web_client
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./src/data:/app/src/data
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ADMIN_USERNAME=geehong
      - ADMIN_PASSWORD=Power@6740
    networks:
      - default
      - shared-network

networks:
  shared-network:
    external: true
